groups:
- name: apache.rules
  rules:
  - alert: ApacheDown
    expr: apache_up{job="apache-exporter-kenzo"} == 0
    for: 5m
    labels:
      severity: error
    annotations:
      summary: "Apache down (instance {{ $labels.instance }})"
      description: "Apache down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
