
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus-kenzo'
    static_configs:
    - targets: ['10.26.26.10:9090']
  - job_name: 'node-kenzo'
    static_configs:
    - targets: ['10.26.26.10:9100','10.26.26.20:9100']
  - job_name: 'docker-kenzo'
    static_configs:
    - targets: ['10.26.26.20:9323']
  - job_name: 'mysql-docker-kenzo'
    static_configs:
    - targets: ['10.26.26.20:32768']
  - job_name: 'apache-exporter-kenzo'
    static_configs:
    - targets: ['10.26.26.10:9117']

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 10.26.26.10:9093

rule_files:
  - "node_rules.yml"
